import React, { useState, useEffect } from 'react';
import axios from 'axios';

const API = process.env.REACT_APP_API_URL;
const C = { card: '#111827', border: '#1f2d3d' };
const CLASSES = ['1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th', '10th', '11th', '12th'];
const CERT_TYPES = ['Transfer Certificate', 'Bonafide Certificate', 'Character Certificate', 'Migration Certificate', 'Experience Certificate'];

export default function TCBonafide() {
    const [certs, setCerts] = useState([]);
    const [form, setForm] = useState({ student_id: '', student_name: '', class: '1st', certificate_type: 'Transfer Certificate', reason: '', issued_by: '' });
    const [adding, setAdding] = useState(false);
    const token = localStorage.getItem('aura_token');
    const headers = { Authorization: `Bearer ${token}` };

    useEffect(() => {
        axios.get(`${API}/api/certificates`, { headers }).then(r => setCerts(r.data)).catch(() => { });
    }, []);

    const handleAdd = async () => {
        await axios.post(`${API}/api/certificates`, form, { headers });
        const r = await axios.get(`${API}/api/certificates`, { headers });
        setCerts(r.data); setAdding(false);
    };

    const printCert = (cert) => {
        const html = `<!DOCTYPE html><html><head><title>${cert.certificate_type}</title>
        <style>
            body { font-family: 'Times New Roman', serif; padding: 40px; color: #000; }
            .header { text-align: center; border-bottom: 3px double #000; padding-bottom: 20px; margin-bottom: 30px; }
            .header h1 { margin: 0; font-size: 28px; }
            .header h2 { margin: 8px 0 0; font-size: 18px; color: #333; }
            .cert-no { text-align: right; font-size: 12px; color: #666; margin-bottom: 20px; }
            .title { text-align: center; font-size: 22px; font-weight: bold; text-decoration: underline; margin: 30px 0; letter-spacing: 2px; }
            .body { font-size: 15px; line-height: 2; text-align: justify; }
            .signatures { display: flex; justify-content: space-between; margin-top: 80px; }
            .sig { text-align: center; width: 200px; }
            .sig .line { border-top: 1px solid #000; padding-top: 8px; font-size: 13px; }
            .seal { text-align: center; margin-top: 20px; font-size: 40px; }
            @media print { body { -webkit-print-color-adjust: exact; } }
        </style></head><body>
        <div class="header">
            <h1>🎓 AuraSync School AI</h1>
            <h2>Indore, Madhya Pradesh | Est. 2024</h2>
            <p style="margin:4px 0 0;font-size:12px">Affiliated to CBSE | Affiliation No: MP-2024-001</p>
        </div>
        <div class="cert-no">Certificate No: ASC-${cert.id}-${new Date().getFullYear()}</div>
        <div class="title">${cert.certificate_type.toUpperCase()}</div>
        <div class="body">
            <p>This is to certify that <strong>${cert.student_name}</strong> was a bonafide student of this school in Class <strong>${cert.class}</strong>.</p>
            <p>This certificate is issued for the purpose of <strong>${cert.reason}</strong>.</p>
            <p>During their tenure, the student has maintained good conduct and character.</p>
            <p>This certificate is issued on <strong>${new Date(cert.issue_date).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}</strong> as per the request of the student/parent.</p>
        </div>
        <div class="seal">🏫</div>
        <div class="signatures">
            <div class="sig"><div class="line">Class Teacher</div></div>
            <div class="sig"><div class="line">Principal<br>AuraSync School AI</div></div>
        </div>
        <div style="text-align:center;margin-top:30px;font-size:10px;color:#999">Generated by AuraSync School AI System | ${new Date().toLocaleString('en-IN')}</div>
        <div style="text-align:center;margin-top:10px" class="no-print">
            <button onclick="window.print()" style="padding:12px 40px;background:#1a365d;color:#fff;border:none;border-radius:8px;font-size:16px;cursor:pointer">🖨️ Print Certificate</button>
        </div>
        </body></html>`;
        const win = window.open('', '_blank', 'width=800,height=900');
        if (win) { win.document.write(html); win.document.close(); }
    };

    return (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 20, fontFamily: "'Segoe UI', sans-serif" }}>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))', gap: 16 }}>
                {[
                    { icon: '📄', label: 'Total Issued', value: certs.length, color: '#4e8ef7' },
                    { icon: '📋', label: 'TC Issued', value: certs.filter(c => c.certificate_type === 'Transfer Certificate').length, color: '#f45b69' },
                    { icon: '✅', label: 'Bonafide', value: certs.filter(c => c.certificate_type === 'Bonafide Certificate').length, color: '#00d97e' },
                ].map(s => (
                    <div key={s.label} style={{ background: C.card, borderRadius: 16, padding: 24, border: `1px solid ${C.border}` }}>
                        <span style={{ fontSize: 22 }}>{s.icon}</span>
                        <p style={{ margin: '8px 0 4px', fontSize: 11, color: '#6b7280', fontWeight: 600, letterSpacing: 1, textTransform: 'uppercase' }}>{s.label}</p>
                        <h2 style={{ margin: 0, fontSize: 24, fontWeight: 800, color: s.color }}>{s.value}</h2>
                    </div>
                ))}
            </div>

            <div style={{ display: 'flex', justifyContent: 'flex-end' }}>
                <button onClick={() => setAdding(!adding)} style={{ padding: '10px 20px', background: '#4e8ef7', border: 'none', borderRadius: 10, color: '#fff', fontWeight: 700, cursor: 'pointer' }}>
                    {adding ? '✕ Cancel' : '+ Issue Certificate'}
                </button>
            </div>

            {adding && (
                <div style={{ background: C.card, borderRadius: 16, padding: 24, border: `1px solid ${C.border}` }}>
                    <p style={{ margin: '0 0 16px', fontWeight: 700, color: '#4e8ef7' }}>📄 Issue Certificate</p>
                    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: 14 }}>
                        {[
                            { label: 'Student ID', key: 'student_id' },
                            { label: 'Student Name', key: 'student_name' },
                            { label: 'Reason/Purpose', key: 'reason' },
                            { label: 'Issued By', key: 'issued_by' },
                        ].map(f => (
                            <div key={f.key} style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
                                <label style={{ fontSize: 12, color: '#9ca3af', fontWeight: 600 }}>{f.label}</label>
                                <input value={form[f.key]} onChange={e => setForm({ ...form, [f.key]: e.target.value })}
                                    style={{ background: '#0d1117', border: `1px solid ${C.border}`, borderRadius: 10, padding: '10px 14px', color: '#f1f5f9', fontSize: 14, outline: 'none' }} />
                            </div>
                        ))}
                        {[
                            { label: 'Class', key: 'class', options: CLASSES },
                            { label: 'Certificate Type', key: 'certificate_type', options: CERT_TYPES },
                        ].map(f => (
                            <div key={f.key} style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
                                <label style={{ fontSize: 12, color: '#9ca3af', fontWeight: 600 }}>{f.label}</label>
                                <select value={form[f.key]} onChange={e => setForm({ ...form, [f.key]: e.target.value })}
                                    style={{ background: '#0d1117', border: `1px solid ${C.border}`, borderRadius: 10, padding: '10px 14px', color: '#f1f5f9', fontSize: 14, outline: 'none' }}>
                                    {f.options.map(o => <option key={o}>{o}</option>)}
                                </select>
                            </div>
                        ))}
                    </div>
                    <button onClick={handleAdd} style={{ marginTop: 16, padding: '11px 24px', background: '#4e8ef7', border: 'none', borderRadius: 10, color: '#fff', fontWeight: 700, cursor: 'pointer' }}>
                        📄 Issue Certificate
                    </button>
                </div>
            )}

            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: 16 }}>
                {certs.map(cert => (
                    <div key={cert.id} style={{ background: C.card, borderRadius: 16, padding: 20, border: `1px solid ${C.border}` }}>
                        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 12 }}>
                            <div>
                                <p style={{ margin: 0, fontWeight: 800, color: '#f1f5f9', fontSize: 15 }}>{cert.student_name}</p>
                                <p style={{ margin: '4px 0 0', fontSize: 12, color: '#6b7280' }}>Class {cert.class}</p>
                            </div>
                            <span style={{ background: '#4e8ef722', color: '#4e8ef7', padding: '3px 10px', borderRadius: 20, fontSize: 10, fontWeight: 700 }}>#{cert.id}</span>
                        </div>
                        <p style={{ margin: '0 0 8px', fontSize: 13, color: '#a78bfa', fontWeight: 700 }}>{cert.certificate_type}</p>
                        <p style={{ margin: '0 0 12px', fontSize: 12, color: '#9ca3af' }}>Reason: {cert.reason}</p>
                        <p style={{ margin: '0 0 12px', fontSize: 11, color: '#6b7280' }}>Issued: {new Date(cert.issue_date).toLocaleDateString('en-IN')}</p>
                        <button onClick={() => printCert(cert)} style={{ width: '100%', padding: '8px', background: '#4e8ef7', border: 'none', borderRadius: 8, color: '#fff', fontWeight: 700, fontSize: 12, cursor: 'pointer' }}>
                            🖨️ Print Certificate
                        </button>
                    </div>
                ))}
                {certs.length === 0 && <p style={{ color: '#6b7280', padding: 20 }}>No certificates issued yet.</p>}
            </div>
        </div>
    );
}